env:
  global:
    - NODE_ENV=test
language: "node_js"
node_js:
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'create database ship_it_test;' -U postgres
after_success:
  - npm run coverage
